---
title: "Performance and Speed Comparisons"
jupyter: python3
toc: true
toc-depth: 3
number-sections: true
number-depth: 2
code-fold: show
code-tools: 
    source: false
    toggle: true
---

::: {.callout-note collapse="false"}
## How this guide benefits you

This guide covers speed and performance comparisons using the `polars` backend. 
:::

# Overview

In version 0.2.0 of `pytimetk`, we are introducing new `polars` engines to many of our functions. Key benefits:

1. You can get between 3X and 500X speed boost on many common time series operations
2. You don't need to know how to use `polars` to gain massive speed boosts
3. Simply turn `engine = 'polars'` to get the 

# Libraries

Run the following code to setup for the performance tests.

```{python}
# Import packages
import pytimetk as tk
import pandas as pd
```



# More Coming Soon...

We are in the early stages of development. But it's obvious the potential for `pytimetk` now in Python. 🐍

- Please [⭐ us on GitHub](https://github.com/business-science/pytimetk) (it takes 2-seconds and means a lot). 
- To make requests, please see our [Project Roadmap GH Issue #2](https://github.com/business-science/pytimetk/issues/2). You can make requests there. 
- Want to contribute? [See our contributing guide here.](/contributing.html) 
