# augment_lags { #pytimetk.augment_lags }

```python
augment_lags(
    data,
    date_column,
    value_column,
    lags=1,
    reduce_memory=False,
    engine='auto',
)
```

Adds lags to a Pandas DataFrame or DataFrameGroupBy object.

The `augment_lags` function takes a Pandas DataFrame or GroupBy object, a
date column, a value column or list of value columns, and a lag or list of
lags, and adds lagged versions of the value columns to the DataFrame.

## Parameters {.doc-section .doc-section-parameters}

| Name         | Type                                   | Description                                                                                                                                                                                                                                                                                                                                                                                                                            | Default    |
|--------------|----------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| data         | DataFrame or GroupBy(pandas or polars) | The input tabular data or grouped data to augment with lagged columns.                                                                                                                                                                                                                                                                                                                                                                 | _required_ |
| date_column  | str                                    | The `date_column` parameter is a string that specifies the name of the column in the DataFrame that contains the dates. This column will be used to sort the data before adding the lagged values.                                                                                                                                                                                                                                     | _required_ |
| value_column | str or list                            | The `value_column` parameter is the column(s) in the DataFrame that you want to add lagged values for. It can be either a single column name (string) or a list of column names.                                                                                                                                                                                                                                                       | _required_ |
| lags         | int or tuple or list                   | The `lags` parameter is an integer, tuple, or list that specifies the number of lagged values to add to the DataFrame.  - If it is an integer, the function will add that number of lagged   values for each column specified in the `value_column` parameter.  - If it is a tuple, it will generate lags from the first to the second   value (inclusive).  - If it is a list, it will generate lags based on the values in the list. | `1`        |
| engine       | (auto, pandas, polars, cudf)           | Execution engine. When "auto" (default) the backend is inferred from the input data type. Use "pandas", "polars", or "cudf" to force a specific backend.                                                                                                                                                                                                                                                                               | `"auto"`   |

## Returns {.doc-section .doc-section-returns}

| Name   | Type      | Description                                                                                                        |
|--------|-----------|--------------------------------------------------------------------------------------------------------------------|
|        | DataFrame | A DataFrame with lagged columns appended. The returned object matches the backend of the input (pandas or polars). |

## Examples {.doc-section .doc-section-examples}

```{python}
import pandas as pd
import polars as pl
import pytimetk as tk


df = tk.load_dataset('m4_daily', parse_dates=['date'])
df
```

```{python}
# Example 1 - Add 7 lagged values for a single DataFrame object (pandas)
lagged_df_single = (
    df
        .query('id == "D10"')
        .augment_lags(
            date_column='date',
            value_column='value',
            lags=(1, 7)
        )
)
lagged_df_single
```
```{python}
# Example 2 - Add lagged values using the polars accessor
lagged_pl = (
    pl.from_pandas(df)
    .group_by('id')
    .tk.augment_lags(
        date_column='date',
        value_column='value',
        lags=(1, 3)
    )
)
lagged_pl
```

```{python}
# Example 3 add 2 lagged values, 2 and 4, for a single DataFrame object (pandas)
lagged_df_single_two = (
    df
        .query('id == "D10"')
        .augment_lags(
            date_column='date',
            value_column='value',
            lags=[2, 4]
        )
)
lagged_df_single_two
```