# augment_holiday_signature { #pytimetk.augment_holiday_signature }

`augment_holiday_signature(data, date_column, country_name='UnitedStates')`

Engineers 4 different holiday features from a single datetime for 80+ countries.

Note: Requires the `holidays` package to be installed. See 
      https://pypi.org/project/holidays/ for more information.

## Parameters

| Name           | Type                                                            | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Default          |
|----------------|-----------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------|
| `data`         | Union\[pd.DataFrame, pd.core.groupby.generic.DataFrameGroupBy\] | The input DataFrame.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | _required_       |
| `date_column`  | str                                                             | The name of the datetime-like column in the DataFrame.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | _required_       |
| `country_name` | str                                                             | The name of the country for which to generate holiday features. Defaults  to United States holidays, but the following countries are currently  available and accessible by the full name or ISO code:      Any of the following are acceptable keys for `country_name`:      Available Countries:    Full Country, Abrv. #1,   #2,   #3     Angola:                 Angola,             AO,   AGO,      Argentina:              Argentina,          AR,   ARG,     Aruba:                  Aruba,              AW,   ABW,     Australia:              Australia,          AU,   AUS,      Austria:                Austria,            AT,   AUT,      Bangladesh:             Bangladesh,         BD,   BGD,     Belarus:                Belarus,            BY,   BLR,     Belgium:                Belgium,            BE,   BEL,     Botswana:               Botswana,           BW,   BWA,     Brazil:                 Brazil,             BR,   BRA,     Bulgaria:               Bulgaria,           BG,   BLG,     Burundi:                Burundi,            BI,   BDI,     Canada:                 Canada,             CA,   CAN,     Chile:                  Chile,              CL,   CHL,     Colombia:               Colombia,           CO,   COL,     Croatia:                Croatia,            HR,   HRV,     Curacao:                Curacao,            CW,   CUW,     Czechia:                Czechia,            CZ,   CZE,     Denmark:                Denmark,            DK,   DNK,     Djibouti:               Djibouti,           DJ,   DJI,     Dominican Republic:     DominicanRepublic,  DO,   DOM,     Egypt:                  Egypt,              EG,   EGY,     England:                England,     Estonia:                Estonia,            EE,   EST,     European Central Bank:  EuropeanCentralBank,     Finland:                Finland,            FI,   FIN,     France:                 France,             FR,   FRA,     Georgia:                Georgia,            GE,   GEO,     Germany:                Germany,            DE,   DEU,     Greece:                 Greece,             GR,   GRC,     Honduras:               Honduras,           HN,   HND,     Hong Kong:              HongKong,           HK,   HKG,     Hungary:                Hungary,            HU,   HUN,     Iceland:                Iceland,            IS,   ISL,     India:                  India,              IN,   IND,     Ireland:                Ireland,            IE,   IRL,     Isle Of Man:            IsleOfMan,     Israel:                 Israel,             IL,   ISR,     Italy:                  Italy,              IT,   ITA,     Jamaica:                Jamaica,            JM,   JAM,     Japan:                  Japan,              JP,   JPN,     Kenya:                  Kenya,              KE,   KEN,     Korea:                  Korea,              KR,   KOR,     Latvia:                 Latvia,             LV,   LVA,     Lithuania:              Lithuania,          LT,   LTU,     Luxembourg:             Luxembourg,         LU,   LUX,     Malaysia:               Malaysia,           MY,   MYS,     Malawi:                 Malawi,             MW,   MWI,     Mexico:                 Mexico,             MX,   MEX,     Morocco:                Morocco,            MA,   MOR,     Mozambique:             Mozambique,         MZ,   MOZ,     Netherlands:            Netherlands,        NL,   NLD,     NewZealand:             NewZealand,         NZ,   NZL,     Nicaragua:              Nicaragua,          NI,   NIC,     Nigeria:                Nigeria,            NG,   NGA,     Northern Ireland:       NorthernIreland,     Norway:                 Norway,             NO,   NOR,     Paraguay:               Paraguay,           PY,   PRY,     Peru:                   Peru,               PE,   PER,     Poland:                 Poland,             PL,   POL,     Portugal:               Portugal,           PT,   PRT,     Portugal Ext:           PortugalExt,        PTE,     Romania:                Romania,            RO,   ROU,     Russia:                 Russia,             RU,   RUS,     Saudi Arabia:           SaudiArabia,        SA,   SAU,     Scotland:               Scotland,     Serbia:                 Serbia,             RS,   SRB,     Singapore:              Singapore,          SG,   SGP,     Slovokia:               Slovokia,           SK,   SVK,     Slovenia:               Slovenia,           SI,   SVN,     South Africa:           SouthAfrica,        ZA,   ZAF,     Spain:                  Spain,              ES,   ESP,     Sweden:                 Sweden,             SE,   SWE,      Switzerland:            Switzerland,        CH,   CHE,     Turkey:                 Turkey,             TR,   TUR,     Ukraine:                Ukraine,            UA,   UKR,     United Arab Emirates:   UnitedArabEmirates, AE,   ARE,     United Kingdom:         UnitedKingdom,      GB,   GBR,   UK,     United States:          UnitedStates,       US,   USA,     Venezuela:              Venezuela,          YV,   VEN,     Vietnam:                Vietnam,            VN,   VNM,     Wales:                  Wales | `'UnitedStates'` |

## Returns

| Type          | Description                                                                                                                                                                                                                                               |
|---------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| pd.DataFrame: | A pandas DataFrame with three holiday-specific features: - is_holiday: (0, 1) indicator for holiday - before_holiday: (0, 1) indicator for day before holiday - after_holiday: (0, 1) indicator for day after holiday - holiday_name: name of the holiday |

## Example

```{python}
import pandas as pd
import pytimetk as tk

# Make a DataFrame with a date column
start_date = '2023-01-01'
end_date = '2023-01-10'
df = pd.DataFrame(pd.date_range(start=start_date, end=end_date), columns=['date'])

# Add holiday features for US
tk.augment_holiday_signature(df, 'date', 'UnitedStates')
```

```{python}
# Add holiday features for France
tk.augment_holiday_signature(df, 'date', 'France')
```