# get_pandas_frequency { #pytimetk.get_pandas_frequency }

`get_pandas_frequency(idx, force_regular=False)`

Get the frequency of a pandas Series or DatetimeIndex.

The function `get_pandas_frequency` takes a Pandas Series or DatetimeIndex as input and returns the inferred frequency of the index, with an option to force regular frequency.

## Parameters

| Name            | Type                          | Description                                                                                                                                                                                                                                                                                                                                              | Default    |
|-----------------|-------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `idx`           | pd.Series or pd.DatetimeIndex | The `idx` parameter can be either a `pd.Series` or a `pd.DatetimeIndex`. It represents the index or the time series data for which we want to determine the frequency.                                                                                                                                                                                   | _required_ |
| `force_regular` | bool                          | The `force_regular` parameter is a boolean flag that determines whether to force the frequency to be regular. If set to `True`, the function will convert irregular frequencies to their regular counterparts. For example, if the inferred frequency is 'B' (business days), it will be converted to 'D' (calendar days). The default value is `False`. | `False`    |

## Returns

| Type   | Description                                                 |
|--------|-------------------------------------------------------------|
| str    | The frequency of the given pandas series or datetime index. |