# make_weekend_sequence { #pytimetk.make_weekend_sequence }

```python
make_weekend_sequence(
    start_date,
    end_date,
    friday_saturday=False,
    remove_holidays=False,
    country=None,
    engine='pandas',
)
```

Generate a sequence of weekend dates within a specified date range,
optionally excluding holidays.

## Parameters {.doc-section .doc-section-parameters}

| Name            | Type                                | Description                                                                                                                                                                                                                                                                                                                                   | Default    |
|-----------------|-------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| start_date      | str or datetime or pd.DatetimeIndex | The start date of the date range.                                                                                                                                                                                                                                                                                                             | _required_ |
| end_date        | str or datetime or pd.DatetimeIndex | The end date of the date range.                                                                                                                                                                                                                                                                                                               | _required_ |
| friday_saturday | bool                                | If True, generates a sequence with Friday and Saturday as weekends. If False (default), generates a sequence with Saturday and Sunday as weekends.                                                                                                                                                                                            | `False`    |
| remove_holidays | bool                                | If True, excludes holidays (based on the specified country) from the generated sequence. If False (default), includes holidays in the sequence.                                                                                                                                                                                               | `False`    |
| country         | str                                 | The name of the country for which to generate holiday-specific sequences. Defaults to None, which uses the United States as the default country.                                                                                                                                                                                              | `None`     |
| engine          | str                                 | The `engine` parameter is used to specify the engine to use for generating a weekend series. It can be either "pandas" or "polars".  - The default value is "pandas".  - When "polars", the function will internally use the `polars` library   for generating a weekend series. This can be faster than using   "pandas" for large datasets. | `'pandas'` |

## Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                                                                      |
|--------|--------|--------------------------------------------------------------------------------------------------|
|        | Series | A Series containing the generated weekend dates. The concrete type matches the requested engine. |

## Examples {.doc-section .doc-section-examples}

```{python}
import pandas as pd
import pytimetk as tk

# United States has Saturday and Sunday as weekends
tk.make_weekend_sequence("2023-01-01", "2023-01-31",
                         friday_saturday = False,
                         remove_holidays = True,
                         country         = 'UnitedStates',
                         engine          = 'pandas')
```

```{python}
# Saudi Arabia has Friday and Saturday as weekends
tk.make_weekend_sequence("2023-01-01", "2023-01-31",
                         friday_saturday = True,
                         remove_holidays = True,
                         country         = 'SaudiArabia',
                         engine          = 'pandas')
```

```{python}
# Saudi Arabia has Friday and Saturday as weekends (polars engine)
tk.make_weekend_sequence("2023-01-01", "2023-01-31",
                         friday_saturday = True,
                         remove_holidays = True,
                         country         = 'SaudiArabia',
                         engine          = 'polars')
```