# timeseries_unit_frequency_table { #pytimetk.timeseries_unit_frequency_table }

```python
timeseries_unit_frequency_table(wide_format=False, engine='pandas')
```

The function `timeseries_unit_frequency_table` returns a pandas DataFrame
with units of time and their corresponding frequencies in seconds.

## Parameters {.doc-section .doc-section-parameters}

| Name        | Type   | Description                                                                                                                                                                                                                                                                                                                    | Default    |
|-------------|--------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| wide_format | bool   | The wide_format parameter determines the format of the output table. If wide_format is set to True, the table will be transposed.                                                                                                                                                                                              | `False`    |
| engine      | str    | The `engine` parameter is used to specify the engine to use for generating the timeseries unit frequency table. It can be either "pandas" or "polars".      - The default value is "pandas".      - When "polars", the function will internally use the `polars` library     for generating a timeseries unit frequency table. | `'pandas'` |

## Returns {.doc-section .doc-section-returns}

| Name   | Type         | Description                                                                                                                                                                                                                           |
|--------|--------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | pd.DataFrame | a pandas DataFrame that contains two columns: "unit" and "freq". The "unit" column contains the units of time (seconds, minutes, hours, etc.), and the "freq" column contains the corresponding frequencies in seconds for each unit. |

## Examples {.doc-section .doc-section-examples}

```{python}
import pytimetk as tk

tk.timeseries_unit_frequency_table()
```

```{python}
# Polars engine example
import pytimetk as tk

tk.timeseries_unit_frequency_table(engine='polars')
```