# week_of_month { #pytimetk.week_of_month }

```python
week_of_month(idx, engine='pandas')
```

The "week_of_month" function calculates the week number of a given date
within its month.

## Parameters {.doc-section .doc-section-parameters}

| Name   | Type                          | Description                                                                                                                                                                                                                                                                                                                                           | Default    |
|--------|-------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| idx    | pd.Series or pd.DatetimeIndex | The parameter "idx" is a pandas Series object that represents a specific date for which you want to determine the week of the month.                                                                                                                                                                                                                  | _required_ |
| engine | str                           | The `engine` parameter is used to specify the engine to use for calculating the week of the month. It can be either "pandas" or "polars".  - The default value is "pandas".  - When "polars", the function will internally use the `polars` library for calculating the week of the month. This can be faster than using "pandas" for large datasets. | `'pandas'` |

## Returns {.doc-section .doc-section-returns}

| Name   | Type      | Description                             |
|--------|-----------|-----------------------------------------|
|        | pd.Series | The week of the month for a given date. |

## Examples {.doc-section .doc-section-examples}

```{python}
import pytimetk as tk
import pandas as pd

dates = pd.date_range("2020-01-01", "2020-02-28", freq="1D")
dates
```

```{python}
# Works on DateTimeIndex
tk.week_of_month(dates, engine='pandas')
```

```{python}
# Works on DateTimeIndex
tk.week_of_month(dates, engine='polars')
```

```{python}
# Works on Pandas Series
dates.to_series().week_of_month()
```

```{python}
# Works on Pandas Series
dates.to_series().week_of_month(engine='polars')
```